.TH "src/utils.c" 3 "Tue Oct 17 2017" "Version 0.2" "EA872 Dictionary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils.c
.SH SYNOPSIS
.br
.PP
\fC#include 'utils\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBgetDate\fP (char *fmt)"
.br
.ti -1c
.RI "char * \fBgetLoggerFileDate\fP ()"
.br
.ti -1c
.RI "char * \fBgetLoggerDate\fP ()"
.br
.ti -1c
.RI "char * \fBgetHTTPDate\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* getDate (char * fmt)"

.SS "char* getHTTPDate ()"

.SS "char* getLoggerDate ()"

.SS "char* getLoggerFileDate ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for EA872 Dictionary from the source code\&.
